### ISSUE TITLE
design the package with standardize linear regression with robust covariance

### ISSUE THREAD

**Issue by clarkliming** [openpharma/RobinCar2#1]
create the package skeleton

- [ ] add design doc (to illustrate the basic designs, will be incorporated into vignettes)
- [x] add script in R folder
- [x] add roxygen chunks to each function
- [ ] add unit tests
- [ ] add vignettes
- [x] update news

**Comment by danielinteractive** [comment]
Random question, did you guys look into https://github.com/mbannick/RobinCar already? Just in a short course at ASA/FDA workshop with the authors, so would be good to know if the new package is complementary
