### ISSUE TITLE
Stratification variables should not adjust the variance

### ISSUE THREAD

**Issue by mbannick** [openpharma/RobinCar2#48]
Stratification variables are currently implemented for both adjustment in the variance (for permuted block and related schemes) and the predictions. We don’t want them to adjust the predictions – this should only happen for Pocock and Simon’s minimization, which we aren’t including in the first release.

@clarkliming I see you made some changes recently for stratification variables but not sure this was implemented. Please close if it was!

**Comment by clarkliming** [comment]
hi @mbannick see https://github.com/openpharma/RobinCar2/pull/44/files#diff-b6beeae35f2696fc4ac401560cc3369fa7169265f67e1ca7739ea415a4650a6f this pr, it should have been updated
