### ISSUE TITLE
implement anhecova robust variance and its report

### ISSUE THREAD

**Issue by clarkliming** [openpharma/RobinCar2#9]
this feature is dependent on #7, however, the work can be started based on some fake data (unbiased predictions)

- [x]  implement the robust variance
- [x] the argument should at least contain "randomization_schema", "formula" (randomization formula, treatment ~ strata, or other forms that can clearly define these information
    - [x] other input, like `y`, `residuals` and `data` are also important
    - [x] not necessarily be a generic or method, because these values can be obtained relatively easy
- [x] follow the logic defined in the RobinCar (and the paper)
- [x] expose the function and add readme

**Comment by hoppanda** [comment]
- [ ] add reporting funciton
- [ ] add unit tests
